# This GitHub Action uses artifacts to pass data between jobs for robust issue creation.

name: Check for Action Items

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  # The first job, named 'check-for-items'. Its purpose is to run the Python script
  # and upload the results as an artifact.
  check-for-items:
    runs-on: ubuntu-latest
    # Add this permissions block to ensure the job can read repository contents.
    permissions:
      contents: read
    outputs:
      create_issue: ${{ steps.check_script.outputs.create_issue }}
      issue_title: ${{ steps.check_script.outputs.issue_title }}
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Check Action Items Script
        id: check_script
        run: python scripts/check_action_items.py

      # This step saves the multi-line issue body to a file
      - name: Save issue body to file
        if: steps.check_script.outputs.create_issue == 'true'
        run: echo "${{ steps.check_script.outputs.issue_body }}" > issue_body.md

      # This step uploads the file as an artifact for the next job
      - name: Upload issue body artifact
        if: steps.check_script.outputs.create_issue == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: issue-data
          path: issue_body.md

  # The second job, named 'create-issue'. Its purpose is to download the artifact and create the issue.
  create-issue:
    needs: check-for-items
    if: needs.check-for-items.outputs.create_issue == 'true'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      
    steps:
      # We need to check out the repo again for the 'gh' command to have context.
      - name: Check out repository
        uses: actions/checkout@v4
        
      # Download the artifact from the previous job
      - name: Download issue body artifact
        uses: actions/download-artifact@v4
        with:
          name: issue-data
          
      - name: Create GitHub Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_TITLE: ${{ needs.check-for-items.outputs.issue_title }}
        run: |
          gh issue create \
            --title "$ISSUE_TITLE" \
            --body-file issue_body.md \
            --label "bug,human-required,agent-reported" \
            --assignee "sagearbor"
