# This GitHub Action checks for new action items and creates a GitHub Issue to notify developers.

name: Check for Action Items

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  # The first job, named 'check-for-items'. Its purpose is to run the Python script.
  check-for-items:
    runs-on: ubuntu-latest
    # Defines the outputs that this job will pass to the next job.
    outputs:
      create_issue: ${{ steps.check_script.outputs.create_issue }}
      issue_title: ${{ steps.check_script.outputs.issue_title }}
      issue_body: ${{ steps.check_script.outputs.issue_body }}
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Check Action Items Script
        id: check_script
        run: python scripts/check_action_items.py

  # The second job, named 'create-issue'. Its purpose is to create the GitHub Issue.
  create-issue:
    needs: check-for-items
    if: needs.check-for-items.outputs.create_issue == 'true'
    runs-on: ubuntu-latest
    permissions:
      issues: write # IMPORTANT: This permission is required to create issues
      
    steps:
      - name: Create GitHub Issue
        # Using the action that we have confirmed the runner can find.
        uses: JasonEtco/create-an-issue@v2
        # This action requires the GITHUB_TOKEN to be passed in the 'env' block.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Sets the issue title using the output from the 'check-for-items' job.
          title: ${{ needs.check-for-items.outputs.issue_title }}
          # Sets the issue body using the output from the 'check-for-items' job.
          body: ${{ needs.check-for-items.outputs.issue_body }}
          # This action requires labels and assignees to be a comma-separated string.
          labels: bug,human-required,agent-reported
          assignees: sagearbor
