# ------------------------------------------------------------
#  Check for Action Items and (if needed) open a GitHub Issue
# ------------------------------------------------------------
name: Check for Action Items

on:
  workflow_dispatch:          # manual trigger
  schedule:
    - cron: '0 * * * *'       # every hour

# All jobs inherit these permissions
permissions:
  contents: read
  issues:   write

jobs:
# ============================================================
# 1. Run your Python script to decide whether to open an issue
# ============================================================
  check-for-items:
    runs-on: ubuntu-latest

    outputs:
      create_issue: ${{ steps.check_script.outputs.create_issue }}
      issue_title:  ${{ steps.check_script.outputs.issue_title }}
      issue_body:   ${{ steps.check_script.outputs.issue_body }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'     # or any version your code needs

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run check_action_items.py
        id: check_script
        run: |
          python scripts/check_action_items.py
        # ----------------------------------------------------
        # Inside scripts/check_action_items.py, write outputs
        # like this (file‑based syntax):
        #
        #   import os
        #   with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
        #       fh.write("create_issue=true\n")
        #       fh.write("issue_title=🚨 Urgent item found\n")
        #       fh.write("issue_body<<EOF\nFull markdown body…\nEOF\n")
        # ----------------------------------------------------

# ============================================================
# 2. Create the GitHub Issue (runs only when create_issue=true)
# ============================================================
  create-issue:
    needs: check-for-items
    if: needs.check-for-items.outputs.create_issue == 'true'
    runs-on: ubuntu-latest

    steps:
      # gh needs a repo checkout so it can locate .git
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create issue with GitHub CLI
        env:
          GH_TOKEN:    ${{ secrets.GITHUB_TOKEN }}              # auth for gh
          ISSUE_TITLE: ${{ needs.check-for-items.outputs.issue_title }}
          ISSUE_BODY:  ${{ needs.check-for-items.outputs.issue_body }}
        run: |
          # Preserve newlines by writing the body to a file
          printf '%s\n' "$ISSUE_BODY" > body.md

          gh issue create \
            --title     "$ISSUE_TITLE" \
            --body-file body.md \
            --label     "bug" \
            --label     "human-required" \
            --label     "agent-reported" \
            --assignee  "sagearbor"

          # Optional clean‑up
          rm -f body.md
