# This GitHub Action checks for new action items and creates a GitHub Issue to notify developers.

name: Check for Action Items

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  check-for-items:
    runs-on: ubuntu-latest
    outputs:
      create_issue: ${{ steps.check_script.outputs.create_issue }}
      issue_title: ${{ steps.check_script.outputs.issue_title }}
      issue_body: ${{ steps.check_script.outputs.issue_body }}
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Check Action Items Script
        id: check_script
        run: python scripts/check_action_items.py

  create-issue:
    needs: check-for-items
    if: needs.check-for-items.outputs.create_issue == 'true'
    runs-on: ubuntu-latest
    permissions:
      issues: write # IMPORTANT: This permission is required to create issues
      
    steps:
      - name: Create GitHub Issue
        # Switched to the correct action that accepts direct text content
        uses: peter-evans/create-issue@v5
        with:
          title: ${{ needs.check-for-items.outputs.issue_title }}
          # Use the 'body' input instead of the invalid 'content'
          body: ${{ needs.check-for-items.outputs.issue_body }}
          labels: |
            bug
            human-required
            agent-reported
          assignees: |
            sagearbor
            another-username # Change as needed
