# This GitHub Action acts as a watchdog to notify developers of new action items.

name: Check for Action Items

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs the workflow automatically every hour
  schedule:
    - cron: '0 * * * *'

jobs:
  check-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Check Action Items Script
        id: check_script # Give this step an ID to access its outputs
        run: python scripts/check_action_items.py

      - name: Send Email Notification
        # This step only runs if the python script's output 'send_email' was 'true'
        if: steps.check_script.outputs.send_email == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com # Or your email provider's SMTP server
          server_port: 465
          # NOTE: You must create these secrets in your repository settings
          # Go to Settings > Secrets and variables > Actions
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${{ steps.check_script.outputs.email_subject }}
          body: ${{ steps.check_script.outputs.email_body }}
          to: user@example.com # Change to your email address
          from: GitHub Actions Bot <github-actions-bot@example.com>
          content_type: text/markdown