# .github/workflows/check-action-items.yml
name: Check for Action Items

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'   # every hour

# Global permissions so every job inherits them
permissions:
  contents: read
  issues: write

jobs:
# --------------------------------------------------
# 1. Detect whether an issue is needed
# --------------------------------------------------
  check-for-items:
    runs-on: ubuntu-latest

    outputs:
      create_issue: ${{ steps.check_script.outputs.create_issue }}
      issue_title:  ${{ steps.check_script.outputs.issue_title }}
      issue_body:   ${{ steps.check_script.outputs.issue_body }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run check script
        id: check_script
        run: python scripts/check_action_items.py
        # Inside your Python script **use the new file‑based output syntax**
        #   with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
        #       fh.write("create_issue=true\n")
        #       fh.write("issue_title=🚨 Something happened\n")
        #       fh.write("issue_body<<EOF\nmultiline body here\nEOF\n")

# --------------------------------------------------
# 2. Create the GitHub Issue (only when needed)
# --------------------------------------------------
  create-issue:
    needs: check-for-items
    if: needs.check-for-items.outputs.create_issue == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Create issue via GitHub CLI
        env:
          # gh will pick this up automatically
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Write the body to a temp file so newlines are preserved
          printf '%s\n' "${{ needs.check-for-items.outputs.issue_body }}" > /tmp/body.md

          gh issue create \
            --title "${{ needs.check-for-items.outputs.issue_title }}" \
            --body-file /tmp/body.md \
            --label "bug" --label "human-required" --label "agent-reported" \
            --assignee "sagearbor"
