# This GitHub Action checks for new action items and creates a GitHub Issue to notify developers.

name: Check for Action Items

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  # The first job, named 'check-for-items'. Its purpose is to run the Python script.
  check-for-items:
    runs-on: ubuntu-latest
    outputs:
      create_issue: ${{ steps.check_script.outputs.create_issue }}
      issue_title: ${{ steps.check_script.outputs.issue_title }}
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Check Action Items Script
        id: check_script
        run: python scripts/check_action_items.py

      # Save issue body to file to handle special characters and multiline content
      - name: Save issue body to file
        if: steps.check_script.outputs.create_issue == 'true'
        run: |
          cat << 'EOF' > issue_body.md
          ${{ steps.check_script.outputs.issue_body }}
          EOF

      # Upload the file as an artifact for the next job
      - name: Upload issue data
        if: steps.check_script.outputs.create_issue == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: issue-data
          path: issue_body.md

  # The second job, named 'create-issue'. Its purpose is to create the GitHub Issue.
  create-issue:
    needs: check-for-items
    if: needs.check-for-items.outputs.create_issue == 'true'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Download issue data
        uses: actions/download-artifact@v4
        with:
          name: issue-data
          
      - name: Create GitHub Issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create \
            --title "${{ needs.check-for-items.outputs.issue_title }}" \
            --body-file issue_body.md \
            --label "bug,human-required,agent-reported" \
            --assignee "sagearbor"