# This GitHub Action uses artifacts to pass data between jobs for robust issue creation.

name: Check for Action Items

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  # The first job, named 'check-for-items'. Its purpose is to run the Python script,
  # pass outputs, and commit the updated notification log.
  check-for-items:
    runs-on: ubuntu-latest
    # This job now needs write permissions to commit the log file.
    permissions:
      contents: write # CORRECTED: Changed from 'read' to 'write'
    outputs:
      create_issue: ${{ steps.check_script.outputs.create_issue }}
      issue_title: ${{ steps.check_script.outputs.issue_title }}
      issue_body: ${{ steps.check_script.outputs.issue_body }}
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Check Action Items Script
        id: check_script
        run: python scripts/check_action_items.py

      - name: Save issue body to file
        if: steps.check_script.outputs.create_issue == 'true'
        run: echo "${{ steps.check_script.outputs.issue_body }}" > issue_body.md

      - name: Upload issue body artifact
        # CORRECTED: Fixed typo from 'check_sctipt' to 'check_script'
        if: steps.check_script.outputs.create_issue == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: issue-data
          path: issue_body.md

      # This step commits the updated notification log back to the repository.
      - name: Commit Notification Log
        if: steps.check_script.outputs.create_issue == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(logs): Update action item notification log"
          # Only commit the specific log file to avoid accidental commits.
          file_pattern: ACTION_ITEMS/notification_log.json
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"

  # The second job, named 'create-issue'. Its purpose is to download the artifact and create the issue.
  create-issue:
    needs: check-for-items
    if: needs.check-for-items.outputs.create_issue == 'true'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Download issue body artifact
        uses: actions/download-artifact@v4
        with:
          name: issue-data
          
      - name: Create GitHub Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_TITLE: ${{ needs.check-for-items.outputs.issue_title }}
        run: |
          gh issue create \
            --title "$ISSUE_TITLE" \
            --body-file issue_body.md \
            --label "bug" \
            --label "human-required" \
            --label "agent-reported" \
            --assignee "sagearbor" \
            --assignee "Teebs4140"
