# This GitHub Action automates proposing the next available tasks.

name: Propose Next Actions

# Allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  propose-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run task proposer script
        run: python scripts/propose_next_tasks.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto-update NEXT_ACTIONS.md"
          file_pattern: "NEXT_ACTIONS.md"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
